language: node_js
dist: xenial

node_js:
    - "lts/*"
env:
    - CXX=g++-5
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5

cache:
    yarn: true

before_install:
  - export TZ='Asia/Shanghai'
 
install:
    - yarn global add vuepress@next

script:
    - yarn install
    - yarn docs:build

notifications:
    email: false

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
    provider: pages
    skip-cleanup: true
    fqdn: docs.qlcchain.online
    local_dir: docs/.vuepress/dist
    github-token: $GITHUB_TOKEN
    # repo: qlcchain/docs
    keep-history: true
    target-branch: master
    on:
        branch: raw