name: Release Pages

on: 
  pull_request:
    branches:
    - raw
jobs:
  build:
    name: Release to GitHub Pages
    runs-on: ubuntu-18.04
    if: contains(github.event.head_commit.message, '[skip ci]') == false && contains(github.event.head_commit.message, '[ci skip]') == false
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: build docs
        run: |
          export TZ='Asia/Shanghai'
          npm i -g yarn
          yarn add vuepress -D
          yarn install
          yarn docs:build
      - name: Release Github Pages
        uses: igolopolosov/github-action-release-github-pages@master
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_PAGES_REPO_AUTHOR: qlcchain-bot
          GITHUB_PAGES_REPO_NAME: qlcchain.github.io
          GITHUB_PAGES_RELEASE_BRANCH: master
          PROJECT_BUILD_FOLDER: docs/.vuepress/dist
          GITHUB_PAGES_CLEANUP_SCRIPT: "rm -rf docs/.vuepress/dist"